### ISSUE TITLE
Mr R cannot add contributors!

### ISSUE THREAD

**Issue by rowbottomn** [ZeroDay-SNP/CyberPatriot-Docs#1]
Hey Zach could you provide elevated permissions just so I can add people?  If not, that's cool. In the future, I will just fork it.

**Comment by zach-sousa-dev** [comment]
For personal GitHub accounts, you only get 2 roles: owner and collaborators - there can only be one owner. I can (maybe) make you the owner, invite everybody else myself, or you could fork it, or we make an organization account for the team. Whatever makes most sense to you.

**Comment by zach-sousa-dev** [comment]
Added everyone as a collaborator.
